### ISSUE TITLE
sys

### ISSUE THREAD

**Issue by lfb6054** [ynulonger/DE_CNN#1]
That one“ sys.arg [1] "Why do you always report errors? Would you  tell me. It can't run normally in CMD.

**Comment by linkingct** [comment]
I have also encountered such a problem. How should I solve it？

**Comment by lfb6054** [comment]
I can't solve it.

**Comment by 11cjxcjxcjxcjx** [comment]
I have also encountered such a problem. How should I solve it？

**Comment by lfb6054** [comment]
That arg [] is the parameter you want to enter. First, you should understand what that parameter represents? You can add me to WeChat to give you an answer. I solved this problem later.

**Comment by 11cjxcjxcjxcjx** [comment]
thank you very much，my wechat number is 18112271016，i am glad to hear from you！！！




下一站
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ynulonger/DE_CNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月13日(星期一) 晚上8:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ynulonger/DE_CNN] sys (#1)





 
That arg [] is the parameter you want to enter. First, you should understand what that parameter represents? You can add me to WeChat to give you an answer. I solved this problem later.

**Comment by ynulonger** [comment]
sorry for making it unclear in the code.

In cnn.py, the comments in Lines 61-64 explain the input arguments expected by the cnn.py
For example, suppose you are going to train a model on subject s01 on the task of arousal classification, using baseline signal and bands 1,2,3. Then the following command line should be used:

python cnn.py with s01 arousal 1 2 3
